<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VCS-X6HRSOWYFCU" failures="1" tests="36" name="Default test" time="0.201" errors="0" timestamp="2025-10-05T03:24:43 IST">
  <testcase classname="repository.AccountRepositoryTest" name="@BeforeMethod setup" time="0.008">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;repository.AccountRepository.clear()&amp;quot; because &amp;quot;this.accountrepo&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "repository.AccountRepository.clear()" because "this.accountrepo" is null
at repository.AccountRepositoryTest.setup(AccountRepositoryTest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:810)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:577)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="repository.AccountRepositoryTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="repository.AccountRepositoryTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="repository.AccountRepositoryTest" name="@BeforeMethod setup" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase classname="repository.AccountRepositoryTest" name="checkDeletion" time="0.001">
    <skipped/>
  </testcase> <!-- checkDeletion -->
  <testcase classname="repository.AccountRepositoryTest" name="checkSave" time="0.001">
    <skipped/>
  </testcase> <!-- checkSave -->
  <testcase classname="repository.AccountRepositoryTest" name="checkfindByAccountNumber" time="0.0">
    <skipped/>
  </testcase> <!-- checkfindByAccountNumber -->
  <testcase classname="repository.AccountRepositoryTest" name="getAllAccounts" time="0.0">
    <skipped/>
  </testcase> <!-- getAllAccounts -->
  <testcase classname="service.AccountServiceTest" name="addAccount" time="0.009"/>
  <testcase classname="service.AccountServiceTest" name="getBalance" time="0.001"/>
  <testcase classname="service.AccountServiceTest" name="deleteAccount" time="0.001"/>
  <testcase classname="service.AccountServiceTest" name="getAllAccounts" time="0.001"/>
  <testcase classname="service.AccountServiceTest" name="checkAccountNotFoundException" time="0.001"/>
  <testcase classname="service.BankStatementServiceTest" name="checkStatement" time="0.009"/>
  <testcase classname="service.TransactionServiceTest" name="accountNotFound" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkAccountNotFoundException" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkInvalidAmountException" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkingInsufficientFundsException" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkDeposit" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkSameAccountTransfer" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkwithdraw" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checktransfer" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkdepositUsingDP" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkdepositUsingDP" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkdepositUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkdepositUsingDP" time="0.006"/>
  <testcase classname="service.TransactionServiceTest" name="checkdepositUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkdepositUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkwithdrawUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkwithdrawUsingDP" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checkwithdrawUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkwithdrawUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checkwithdrawUsingDP" time="0.001">
    <failure type="exception.InsufficientFundsException" message="Insufficient Funds">
      <![CDATA[exception.InsufficientFundsException: Insufficient Funds
at service.TransactionService.withdraw(TransactionService.java:49)
at service.TransactionServiceTest.checkwithdrawUsingDP(TransactionServiceTest.java:135)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- checkwithdrawUsingDP -->
  <testcase classname="service.TransactionServiceTest" name="checkwithdrawUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checktransferUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checktransferUsingDP" time="0.002"/>
  <testcase classname="service.TransactionServiceTest" name="checktransferUsingDP" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checktransferUsingDP" time="0.0"/>
  <testcase classname="service.TransactionServiceTest" name="checktransferUsingDP" time="0.001"/>
  <testcase classname="service.TransactionServiceTest" name="checktransferUsingDP" time="0.0"/>
</testsuite> <!-- Default test -->
